### PR TITLE
Fixes #38 - Now grabs configuration value from Hand-ack message and a…

### LINKED ISSUE #38: Accept configuration message and react accordingly

### PR DESCRIPTION
**Pull request by kamladi**
…dds it as param to new outlet

New property in outlet database: 'hardware_version'. Saving it as a string for now, but if we want to specify it as an integer, we can do that.

Since this features hasn't been added network-side, someone check me to make sure I'm making the right assumptions about the format?

### CODE REVIEW

**Comment by dansantorojr** [comment]
Does it make more sense to save it as an integer because it's going to come to you as a byte of info and is naturally a number?

**Comment by dansantorojr** [comment]
Also...line 104 says: "var payloadValues = payload.split(',');" .... but if you are sending native bytes over the serial bus then there are no commas to split on. For this sort of thing I imagined you'd have an equivalent parser/assembler for the server, similar to what we have for the nodes/gateway. 

Can you explain why we are splitting on commas here? I haven't looked through all the code, so it's certainly reasonable that I don't fully understand something on your end.

**Comment by kamladi** [comment]
We aren't sending native byte messages from gateway => server yet. I wanted to get all the messages working before converting that over. Server => gateway messages were converted because there's only one message to worry about (commands).

What value, specifically, will the configuration value be? Will it be simply an integer (1, 2, ...), or a string ('v1', 'v2,...)?

**Comment by dansantorojr** [comment]
Yeah, I say we either 
(1) set it as a sequential number or 
(2) set it as a two byte date code. Something like:: 0x[M][YY][R]
- M = 1-B for the months of year (3 = March) 
- YY = 00-FF for the year (10 = 2016)
- R = 0-F for revision (0 = Rev. 0)

**Comment by dansantorojr** [comment]
Also, I misunderstood what was complete, I thought the full server <-> gateway comms were just native bytes now. Shouldn't that be the first priority? I know they are theoretically the same priority, but that will reduce double work. Get the message protocol straightened up, and then start adding messages / fields.

**Comment by kamladi** [comment]
I only have one firefly right now, so I can test server=>gateway parsing, but I can't test gateway=>server yet since I want to test with an extra node which can generate sample data/cmd-ack messages. Figured I'd knock this out in the meantime until we met up...

**Comment by dansantorojr** [comment]
Thoughts on the hardware version? I think it'd be cool to do a date code...kind of a more realistic use of it. Our two hardware versions could would be 0x3100 and 0x4100. If we wanna get real fancy we could make a 0x4101 by not populating a sensor or something like that. Not necessary, but just to show that we can handle different versions of hardware and failed sensors, etc.

**Pull request merged**
